modLoader="javafml"
loaderVersion="[31,)"
license="LGPL-3.0-or-later"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="ImToggle"
    description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minor_mc_version}]"
    ordering="NONE"
    side="BOTH"